function [ReportParagraph] = LpGenReport(Report)
ReportParagraph={};
if ~isempty(Report)
    Fields=fieldnames(Report);
    for RepId=1:numel(Fields)
        CurRepName=Fields{RepId};
        ReportParagraph{end+1}=...
            [Report.(CurRepName).DscStr ':' ...
            ' Min=' num2str(round(Report.(CurRepName).Min)) ...
            ' Max=' num2str(round(Report.(CurRepName).Max)) ...
            ' Total=' num2str(round(Report.(CurRepName).Total)) ...
            ' Mean=' ...
            num2str(round(Report.(CurRepName).Total ...
            /Report.(CurRepName).nTimes)) ...
            ];
    end
end
end

