function [Db] = LpGetUserInput_XLS(InputXlsFullPath)
%% Description
%% StandAlone
if true
    %% Select file
    if ~exist('InputXlsFullPath','var')
        DialogTitle='Select user input XLS file';
        [InputXlsName,InputXlsPath] = uigetfile('*.xlsm',DialogTitle);
        InputXlsFullPath=fullfile(InputXlsPath,InputXlsName);
    end
end
%% Body
if true
    %% Fetch data
    if true
        %% DbElelements
        DbElelements={ ...
            'My details', ...
            'Market', ...
            'Initial position', ...
            'Incomes', ...
            'Expenses', ...
            'Assets', ...
            'Loans', ...
            'Savings', ...
            };
        FuncNameAux=lower(regexprep(DbElelements,' ',''));
        Db=AUX.LpDefaultDbConstructor;
        for DbElId=1:numel(DbElelements)
            [~,~,XlsData]=xlsread(InputXlsFullPath,DbElelements{DbElId},'','basic');
            TmpCmnd=[ ...
                'Db=' ...
                'AUX.LpProcessXlsData_' FuncNameAux{DbElId} ...
                '(Db,XlsData);' ...
                ];
            eval(TmpCmnd);
        end        
    end
end
end

