function [Contributors,Position] = ...
    LpUpdateContributors_LoanDynamics(Position,Contributors,LoanCfg)
%% Description
%{
Here we update the contributors in event of entering to saving
%}
%% StandAlone
if ~exist('Position','var')
    Position=AUX.LpNullPositionConstructor;
end
if ~exist('Contributors','var')
    Contributors = AUX.LpNullContributorsConstructor();
end
if ~exist('LoanCfg','var')
    LoanCfg = AUX.LpDefaultLoanCfgConstructor;
end
%% Aux
FinishLoanThreshold=1;
[InterestPayment,PrincipalPayment,Position]=...
    AUX.LpProcessLoan(Position,LoanCfg);
LoanName=AUX.LpConvertStringToValidFieldName(LoanCfg.DscStr);
Contributors.Duties.LoanPayment.(...
    LoanName...
    )=PrincipalPayment;
CurPayment=InterestPayment+PrincipalPayment;
Contributors.Report.Loans.(...
    LoanName...
    ).Payment=CurPayment;
Contributors.Report.Loans.(...
    LoanName...
    ).InterestPayment=InterestPayment;
Contributors.Report.Loans.(...
    LoanName...
    ).PrincipalPayment=PrincipalPayment;
ClosedLoanFlg=0;
%% Body
if true
    %% Cash
    Contributors.Expense= ...
        Contributors.Expense ...
        +CurPayment;
    %% Loans
    Contributors.Duties.Loans=...
        Contributors.Duties.Loans ...
        -PrincipalPayment;
    %% Finished
    LoanFieldName=AUX.LpConvertStringToValidFieldName(LoanCfg.DscStr);
    PreviousPrincipal=...
        Position.Duties.ActiveLoans.(LoanFieldName).Principal;
    if (PreviousPrincipal-PrincipalPayment)<FinishLoanThreshold
        Contributors.Duties.ClosedLoans=...
            {Contributors.Duties.ClosedLoans{:} ...
            LoanCfg.DscStr};
        ClosedLoanFlg=1;
    end
    %% Report
    if strcmpi(LoanCfg.Report,'ON')
        FieldName=...
            AUX.LpConvertStringToValidFieldName(...
            LoanCfg.DscStr ...
            );
        Contributors.Report.Expenses.(FieldName).DscStr=...
            LoanCfg.DscStr;
        Contributors.Report.Expenses.(FieldName).Amount=...
            CurPayment;
    end
end
%% LOG
Contributors.Log={Contributors.Log{:} , ...
    ['Loan:"' LoanCfg.DscStr '":Dynamics']};
if ClosedLoanFlg
    Contributors.Log={Contributors.Log{:} , ...
        ['Loan:"' LoanCfg.DscStr '":Finished(Not existed)']};
end
end

